"""add is_active, category

Revision ID: 624c7592906f
Revises: 41b322173c4f
Create Date: 2024-11-19 16:16:48.011132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624c7592906f'
down_revision = '41b322173c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
